name: Build & compile C or Go project

on:
  workflow_dispatch:
             branches:
               - "main"

jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Generate
      uses: skx/github-action-build@master
      with:
        builder: .github/build/run.sh

